maps<-data.frame(foo=c(10,9))
maps<- read.csv("MapsThatChangedOurWorld_StoryMap_Data.csv",sep=";")
colnames(maps) <- names(maps[1,])
maps$Latitude <- gsub('N', '', maps$Latitude)
maps$Latitude <- as.numeric(maps$Latitude)
print(maps)
idx <- which(grepl('W', maps$Longitude))
print(idx)
maps
maps$Longitude <- gsub('[EW]', '', maps$Longitude)
maps$Longitude <- as.numeric(maps$Longitude)
print(maps)
maps$Year <- gsub('AD', '', maps$Year)
maps$Year <- as.numeric(maps$Year)
print(maps)
maps$Longitude <- as.numeric(maps$Longitude)
maps$Latitude <- as.numeric(maps$Latitude)
head(maps)
hist(maps$Year, breaks = 10, main = "Histogram of Year", xlab = "Year")
head(maps)
maps$Longitude[idx] <- maps$Longitude[idx] * -1
head(maps)
finalResult <- maps[, c("Longitude", "Latitude", "Year")]
print(finalResult)

